FROM php:fpm
RUN apt-get update && \
        apt-get install -y \
            bash grep \
            curl libcurl4-openssl-dev libcurl4 libssl-dev

RUN pecl install -of redis && docker-php-ext-enable redis

WORKDIR /var/www/html