drop table if exists movie, movie_attr, movie_attr_type, movie_attr_value cascade;

create table movie
(
    id   int primary key generated by default as identity,
    name varchar(255) not null unique
);

create table movie_attr_type
(
    id   int primary key generated by default as identity,
    name varchar(63) not null unique
);

create table movie_attr
(
    id      int primary key generated by default as identity,
    name    varchar(63) not null unique,
    type_id int         not null references movie_attr_type (id)
);

create table movie_attr_value
(
    movie_id int not null references movie (id),
    attr_id  int not null references movie_attr (id),
    date     timestamp with time zone,
    bool     bool,
    text     varchar,
    double   double precision,
    numeric  numeric(18, 2),
    constraint movie_attr_unique unique (movie_id, attr_id)
);
