CREATE USER readuser LOGIN PASSWORD 'xezive331!';
GRANT CONNECT ON DATABASE crazydope TO readuser;
GRANT USAGE ON SCHEMA theater TO readuser;
GRANT SELECT ON ALL TABLES IN SCHEMA theater TO readuser;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA theater TO readuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA theater GRANT SELECT ON TABLES TO readuser;