#!/bin/bash
if [ ! $# -eq 2 ]
then
echo wrong count of arguments
exit 1
fi
reg='^-?[0-9]+\.?[0-9]*$'
if ! [[ $1 =~ $reg && $2 =~ $reg ]]
then
echo wrong arguments
exit 1 
fi
echo first number - $1
echo second number - $2
echo summ =
echo $1+$2 |bc


