#!/bin/bash

echo "Миникалькулятор"
echo $1 $2

if ! [[ $1 =~ ^-?([0-9]*[.])?[0-9]+$ ]]; then
    echo "Первое число - не корректно";
    exit;
fi

if ! [[ $2 =~ ^-?([0-9]*[.])?[0-9]+$ ]]; then
    echo "Второе число - не корректно";
    exit;
fi

perl -e "print $1 + $2"
echo ""
awk "BEGIN {z= $1 + $2; print z}"
echo  "$1 + $2" | bc
