INSERT INTO public.movies ("name")
VALUES ('Green Book'),
       ('Django Unchained'),
       ('Now You See Me'),
      ('The Godfather '),
     ('Forrest Gump'),
    ('Star Wars'),
   ('The Lion King'),
   ('Intouchables'),
   ('WALL·E'),
   ('Joker'),
   ('Toy Story 3'), ('Batman Begins'),
  ('Bacheha-Ye aseman'),('The Wolf of Wall Street'),('Lock, Stock and Two Smoking Barrels'),('Jurassic Park'),('Kill Bill: Vol. 1 '),('Logan'),
 ('Indiana Jones and the Last Crusade');

INSERT INTO public.movie_attrs_types ("name")
VALUES ('Текст'),
       ('Сумма'),
       ('Время'),
       ('Оценка'),
       ('Служебная дата'),
       ('Информационная дата');

INSERT INTO public.movie_attrs ("name", type_id)
VALUES ('Режисёр', 1),
       ('Премьера РФ', 3),
       ('Премьера мир', 3),
       ('Бюджет', 2),
       ('Сборы РФ', 2),
       ('Сборы мир', 2),
       ('Длительность', 4),
       ('Слоган', 1),
       ('Рейтинг', 5),
       ('Выпуск на DVD', 6),
       ('Выпуск в онлайн-кинотеатрах', 6),
       ('Запуск рекламы', 6);

INSERT INTO public.movie_attrs_values (movie_id, attr_id, text_value, int_value, date_value, time_value, float_value)
VALUES (1, 1, 'Питер Фаррелли', NULL, NULL, NULL, NULL),
       (1, 2, task_date(), NULL, NULL, NULL, NULL),
       (1, 3, NULL, NULL, task_date(), NULL, NULL),
       (1, 4, NULL, 23000000, NULL, NULL, NULL),
       (1, 5, NULL, 9319659, NULL, NULL, NULL),
       (1, 6, NULL, 321752656, NULL, NULL, NULL),
       (1, 7, NULL, NULL, task_date(), NULL, NULL),
       (1, 8, NULL, NULL, NULL, '02:10:00', NULL),
       (1, 9, '«Inspired by a True Friendship»', NULL, NULL, NULL, NULL),
       (1, 10, NULL, NULL, NULL, NULL, 8.3),
       (1, 12, NULL, NULL, task_date(), NULL, NULL),
       (2, 1, 'Квентин Тарантино', NULL, NULL, NULL, NULL),
       (2, 2, task_date(), NULL, NULL, NULL, NULL),
       (2, 3, NULL, NULL, task_date(), NULL, NULL),
       (2, 4, NULL, 100000000, NULL, NULL, NULL),
       (2, 5, NULL, 15990907, NULL, NULL, NULL),
       (2, 6, NULL, 425368236, NULL, NULL, NULL),
       (2, 7, NULL, NULL, task_date(), NULL, NULL),
       (2, 8, NULL, NULL, NULL, '02:10:00', NULL),
       (2, 9, '«Они забрали его свободу. Он заберёт у них всё»', NULL, NULL, NULL, NULL),
       (2, 10, NULL, NULL, NULL, NULL, 8.2),
       (2, 12, NULL, NULL, task_date(), NULL, NULL),
       (3, 1, 'Луи Летерье', NULL, NULL, NULL, NULL),
       (3, 2, task_date(), NULL, NULL, NULL, NULL),
       (3, 3, NULL, NULL, task_date(), NULL, NULL),
       (3, 4, NULL, 75000000, NULL, NULL, NULL),
       (3, 5, NULL, 20956962, NULL, NULL, NULL),
       (3, 6, NULL, 351723989, NULL, NULL, NULL),
       (3, 7, NULL, NULL, task_date(), NULL, NULL),
       (3, 8, NULL, NULL, NULL, '02:10:00', NULL),
       (3, 9, '«Чем вы ближе, тем меньше вы видите»', NULL, NULL, NULL, NULL),
       (3, 10, NULL, NULL, NULL, NULL, 7.7),
       (3, 12, NULL, NULL, task_date(), NULL, NULL);
       
INSERT INTO public.customers ("name")
VALUES ('Dale Blanchard'),
		('Siena Vaughan'),
		('Danna Rich'),
		('Jeffrey Cooper'),
		('Cierra Dickson'),
		('Jayla Pollard'),
		('Alonzo Haynes'),
		('Melina Hendricks'),
		('Nathanial Haynes'),
		('Madyson Herring'),
		('Rodney Dunlap'),
		('Matthew Santana'),
		('Lorenzo Cantu'),
		('Atticus Arroyo'),
		('Estrella Watts'),
		('Kenyon Santana'),
		('Gaven Sims'),
		('Nico Bennett'),
		('Conner Ortega'),
		('Sharon Calderon'),
		('Enrique Wilcox'),
		('Clayton Trevino'),
		('Gaige Friedman'),
		('Tristian Kirby'),
		('Franco Rich'),
		('Lucian Kaufman'),
		('Damari Horne'),
		('Heidi Leon'),
		('Lilian Meadows'),
		('Eve Weiss'),
		('Nelson Knox'),
		('Alison Hooper'),
		('Nathan Mcmahon'),
		('Alisson Payne'),
		('Pierce Potter'),
		('Kathleen Carrillo'),
		('Quentin Rocha'),
		('Jada Mccarthy'),
		('Matias Crawford'),
		('Cameron Calderon'),
		('Alexis Hammond'),
		('Mckayla Colon'),
		('Yadira Mills'),
		('Anahi Cochran'),
		('Princess Johnston'),
		('Eve Gilmore'),
		('Justice Hobbs'),
		('Vicente West'),
		('Sonny Fischer'),
		('Kennedi Walker'),
		('Saniya Chen'),
		('Mason Goodwin'),
		('Athena Sawyer'),
		('Yaretzi Bartlett'),
		('Cale Downs'),
		('Aaliyah French'),
		('Eileen Newman'),
		('Caitlyn Rowe'),
		('Mariah Price'),
		('Kierra Dunn'),
		('Jaden Ferrell'),
		('Shea Jones'),
		('Tanner Dalton'),
		('Jeremy Parsons'),
		('Jordyn Leonard'),
		('Kara Steele'),
		('Clarence Terry'),
		('Geovanni Barber'),
		('Paityn Bernard'),
		('Kade Novak'),
		('Bryanna Stevens'),
		('Santino Morgan'),
		('Adison Snow'),
		('Jadyn Espinoza'),
		('Ashlee Parker'),
		('Lola Hutchinson'),
		('Sadie Obrien'),
		('Yahir Gallagher'),
		('Ana Houston'),
		('Ashlyn Hooper'),
		('Lincoln Powell'),
		('Mara Archer'),
		('Shaun Duffy'),
		('Sonia Schmitt'),
		('Jazmyn Meyers'),
		('Dax Cain'),
		('David Rubio'),
		('Esteban Murphy'),
		('Annalise Mcdaniel'),
		('Yazmin Fuller'),
		('Frank Johnson'),
		('Irvin Mathews'),
		('Bronson Chase'),
		('Lindsey Byrd'),
		('Braxton Beasley'),
		('Valentin Ochoa'),
		('Leroy Kaiser'),
		('Thomas Freeman'),
		('Natalee Ritter'),
		('Daniel Barnett');
      
INSERT INTO public.halls ("name")
SELECT
('Hall #' || halls.id::text)
FROM generate_series(1, 5) AS halls(id);

INSERT INTO public.seats_type (code)
values  ('vip'),
        ('common'),
        ('comfort');

SELECT fill_seats_fake_data();