#!/usr/bin/env bash
SETCOLOR_SUCCESS="echo -en \\033[1;32m"
SETCOLOR_FAILURE="echo -en \\033[1;31m"
SETCOLOR_NORMAL="echo -en \\033[0;36m"
success=false

$SETCOLOR_NORMAL
echo -n "Введите первое число "
read num1
if ! [[ $num1 =~ ^-?[0-9]+[.]?[0-9]*$ ]]; then
 $SETCOLOR_FAILURE
 echo "Введено не число"
else
 $SETCOLOR_SUCCESS
 echo -n "$(tput hpa $(tput cols))$(tput cub 6)[OK]"
 success=true
 $SETCOLOR_NORMAL
 echo
fi

$SETCOLOR_NORMAL
echo -n "Введите второе число "
read num2
if ! [[ $num2 =~ ^-?[0-9]+[.]?[0-9]*$ ]]; then
 success=false
 $SETCOLOR_FAILURE
 echo "Введено не число"
else
 $SETCOLOR_SUCCESS
 echo -n "$(tput hpa $(tput cols))$(tput cub 6)[OK]"
 $SETCOLOR_NORMAL
 echo
fi

if "$success"; then
 $SETCOLOR_NORMAL
 echo  $num1 + $num2 | bc
else
 $SETCOLOR_FAILURE
 echo "Скрипт завершён"
fi
