#!/usr/bin/env php
<?php

declare(strict_types=1);

use Composer\Autoload\ClassLoader;
use Socket\Socket;

/**
 * @var ClassLoader $loader
 */
$loader = require __DIR__.'/../vendor/autoload.php';

$socketConfig = parse_ini_file('config/socket.ini', true, INI_SCANNER_TYPED);
$options = getopt('m::', ['message::']);

$message = null;
if (isset($options['m'])) {
    $message = (string)$options['m'];
}
if (isset($options['message'])) {
    $message = (string)$options['message'];
}

$socket = new Socket(AF_UNIX, SOCK_DGRAM);
$app = new App($socket, $socketConfig['client']['address'], $socketConfig['server']['address']);
$app->send($message);
