#!/usr/bin/php
<?php
defined('APPLICATION_PATH')
|| define('APPLICATION_PATH', realpath(dirname(__FILE__) . '/..'));

require_once APPLICATION_PATH . '/vendor/autoload.php';

$consumer = new \Otus\Consumers\MessageConsumer();
$consumer->startConsume();