<?php


namespace App;


use Illuminate\Support\ServiceProvider;

class AmqpServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}