<?php

define('ROOT_PATH', __DIR__);
define('VENDOR_PATH', ROOT_PATH . DIRECTORY_SEPARATOR . '../vendor');
define('SQL_SCRIPTS_PATH', ROOT_PATH . DIRECTORY_SEPARATOR . 'Database'. DIRECTORY_SEPARATOR .'sqls');