#!/bin/bash
# calculate sum
regEx='^[0-9]+([.][0-9]+)?$'

until [[ $var1 =~ $regEx ]]
do
echo -n "Enter the first number 'var1': "
read var1
if ! [[ $var1 =~ $regEx ]]
then
echo "error: Not a number" 
fi
done


until [[ $var2 =~ $regEx ]]
do
echo -n "Enter the second number 'var2': "
read var2
if ! [[ $var2 =~ $regEx ]]
then
   echo "error: Not a number"
fi
done

echo -n  'Sum is ' 
echo $var1 + $var2 | bc
