drop table if exists employees;

create table employees
(
    id      int primary key generated by default as identity,
    name    varchar(255),
    surname varchar(255),
    phone   varchar(255),
    job     varchar(255),
    salary  int check (salary >= 0)
);
